## OS

In [13]:
import os
os.getcwd()

'D:\\_Python'

In [63]:
os.chdir('D:\\_Python')

In [68]:
os.path.exists('D:\\_Python')

True

In [69]:
if os.path.exists("Test.txt"):
    os.remove("Test.txt")

In [70]:
os.mkdir("WorkingFiles") #creates new directory
os.rmdir("WorkingFiles") #removed directory

In [23]:
folder = 'D:\\_Python'
os.listdir(folder)  # lists all subfolders and files

['.pylint.d',
 'example.csv',
 'example.xlsx',
 'example_csv.csv',
 'General useful',
 'General_useful_code',
 'Ice Hockey Data Analysis',
 'Literature',
 'MarketAnalysis.py',
 'martingale.py',
 'misc projects',
 'not completed',
 'notes.txt',
 'Option Analytics',
 'pokus',
 'pokus1.txt',
 'pokus2.txt',
 'pokus2.txt.npy',
 'Portfolio analytics.py',
 'roulette.py',
 'Tutorial replications']

<br> r makes it a "raw string literal" -> python will treat \ as an escape character, otherwise it could treat \n as a new line
<br> \\ is also a literal backslash
<br> so python normally treats normal backslash \ as special characters - \n or \t

In [16]:
file1 = 'D:\\_Python\\pokus1.txt'
file2 = r'D:\_Python\pokus2.txt'

file1, file2

('D:\\_Python\\pokus1.txt', 'D:\\_Python\\pokus2.txt')

In [19]:
f = open('D:\_Python\pokus2.txt', "r")   # does not work, bcause python interprests \ as an escape character

<>:1: SyntaxWarning: invalid escape sequence '\_'
<>:1: SyntaxWarning: invalid escape sequence '\_'
C:\Users\pavel\AppData\Local\Temp\ipykernel_31920\2228621066.py:1: SyntaxWarning: invalid escape sequence '\_'
  f = open('D:\_Python\pokus2.txt', "r")   # does not work

In [20]:
f = open(r'D:\_Python\pokus2.txt', "r")  # works - use raw string

In [21]:
f = open('D:\\_Python\\pokus2.txt', "r") # works - escape the backlash

In [40]:
f = open('D:/_Python/pokus2.txt', "r")   # works - use forward slash

Even better is to use Pathlib

### Pathlib

why to use Path?
<br> the code will work across operating systems
<br> automatically uses correct sepperator \ / 
<br> the code is easier to manipulate

In [2]:
from pathlib import Path

In [30]:
f = open(Path(r'D:\_Python\pokus2.txt'), "r") # this is one way to do it. Ideally I should close the file, so that other programs can access it.
f.read()
f.close()

In [35]:
folder = Path(r'D:\_Python')
file = folder / "pokus2.txt"
f = open(file, "r")

In [14]:
# but if something happens in between, the file might still not be accessible to other programs, so a better way is to use with:
with open(r'D:\_Python\pokus2.txt', "r") as f: #it will automatically call the close statement when the execution leaves the block
    print(f.read())

first line
second line

In [15]:
# check if the path exists
p = Path(r'D:\_Python\pokus2.txt')
p.exists()

True

In [18]:
# is the path a file?
p = Path(r'D:\_Python')
p.is_file()

False

In [2]:

Path(__name__)

WindowsPath('__main__')

In [3]:
Path(__name__).resolve() # converts to an absolute path

WindowsPath('D:/_Python/General_useful_code/__main__')

In [4]:
Path(__name__).resolve().parent # gets the directory containing the script

WindowsPath('D:/_Python/General_useful_code')

In [5]:
Path(__name__).resolve().parent.parent # I can put there ".parent" even more times

WindowsPath('D:/_Python')

In [8]:
BASE_DIR = Path(__name__).resolve().parent
DATA_DIR = BASE_DIR / "Option Analytics"  # or config-driven

In [32]:
'''
 You can pass a string of a folder or filename to Path() to create a Path object of that folder or filename. 
 As long as the leftmost object in an expression is a Path object, you can use the / operator to join together Path objects or strings.
 Compare below
'''

Path('spam') / 'some_folder'
Path('spam') / Path('some_folder')
Path('spam') / Path('some_folder/a')
Path('spam') / Path('some_folder','a')
Path(r'.\spam')

WindowsPath('spam')

In [33]:
Path.home() # 'home' directory

WindowsPath('C:/Users/pavel')

In [85]:
Path.cwd() #current working directory use oc.chdir() to change it...

WindowsPath('D:/_Python')

## Pandas

### Excel

In [87]:
import pandas as pd

sheet1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
sheet2 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

file_name_xls = 'example.xlsx'
sheet1.to_excel(file_name_xls, sheet_name='Example1', )

In [90]:
# more options with ExcelWriter
with pd.ExcelWriter(file_name_xls) as writer:
    sheet1.to_excel(writer, sheet_name='Sheet1')
    sheet2.to_excel(writer, sheet_name='Sheet2')
    
pd.read_excel(file_name_xls, sheet_name='Sheet1', index_col=0, header= None)

     1  2
0
NaN  a  b
0.0  1  4
1.0  2  5
2.0  3  6

### csv

In [91]:
file_name_csv = 'example_csv.csv'
sheet1.to_csv(file_name_csv)
pd.read_csv(file_name_csv)

   Unnamed: 0  a  b
0           0  1  4
1           1  2  5
2           2  3  6

In [92]:
sheet1.to_csv(file_name_csv, index=False, sep= ',')
pd.read_csv(file_name_csv)

   a  b
0  1  4
1  2  5
2  3  6

## File Manipulations

<br> "r" - Read - Default value. Opens a file for reading, error if the file does not exist
<br> "a" - Append - Opens a file for appending, creates the file if it does not exist
<br> "w" - Write - Opens a file for writing, creates the file if it does not exist
<br> "x" - Create - Creates the specified file, returns an error if the file exists

### Read

In [11]:
with open(Path(r'D:\_Python\pokus2.txt'), "r") as f:
    print(f.read())

first line
second line

In [5]:
# specify the number of characters to be read
with open(Path(r'D:\_Python\pokus2.txt'), "r") as f:
    print(f.read(5))

first

In [8]:
# or read the entire first line
with open(Path(r'D:\_Python\pokus2.txt'), "r") as f:
    print(f.readline())

first line

In [10]:
# it iterates row over row
with open(Path(r'D:\_Python\pokus2.txt'), "r") as f:
    print(f.readline())
    print(f.readline())

first line

second line

In [21]:
# to go through the whole file line by line
for i in open(Path(r'D:\_Python\pokus2.txt'), "r"):
    print(i)

first line

second line

In [28]:
f.close() # make sure to close the file so that other processes can access it

### Amend

In [32]:
# a just appends the file
with open(Path(r'D:\_Python\pokus2.txt'), "a") as f:
    f.write('just added a line\n')
    f.close() # not neccessary here because I used "with"

with open(Path(r'D:\_Python\pokus2.txt'), "r") as f: print(f.read())

first line
second line
just added a line

### Write

In [31]:
# w rewrites the entire file
with open(Path(r'D:\_Python\pokus2.txt'), "w") as f:
    f.write('first line\n')
    f.write('second line\n')
    f.close() # not neccessary here because I used "with"

with open(Path(r'D:\_Python\pokus2.txt'), "r") as f: print(f.read())

first line
second line

### Create a file - X

In [66]:
new = open('created_file.txt', 'x')
new.close()

with open(Path(os.getcwd()) / "created_file.txt", "w") as f:
    f.write('first line')
    
with open(Path(os.getcwd()) / "created_file.txt", "r") as f:
    print(f.read())

first line

In [67]:
# removes a file
os.remove('created_file.txt')

### Platform

In [72]:
import platform

platform.system()

'Windows'

In [73]:
dir(platform)

['AndroidVer',
 'IOSVersionInfo',
 '_Processor',
 '_WIN32_CLIENT_RELEASES',
 '_WIN32_SERVER_RELEASES',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_comparable_version',
 '_default_architecture',
 '_follow_symlinks',
 '_get_machine_win32',
 '_java_getprop',
 '_mac_ver_xml',
 '_node',
 '_norm_version',
 '_os_release_cache',
 '_os_release_candidates',
 '_parse_os_release',
 '_platform',
 '_platform_cache',
 '_sys_version',
 '_sys_version_cache',
 '_syscmd_file',
 '_syscmd_ver',
 '_uname_cache',
 '_unknown_as_blank',
 '_ver_stages',
 '_win32_ver',
 '_wmi',
 '_wmi_query',
 'android_ver',
 'architecture',
 'collections',
 'freedesktop_os_release',
 'functools',
 'ios_ver',
 'itertools',
 'java_ver',
 'libc_ver',
 'mac_ver',
 'machine',
 'node',
 'os',
 'platform',
 'processor',
 'python_branch',
 'python_build',
 'python_compiler',
 'python_implementation',
 'python_revision',
 'python_version',
 'python_version_tuple',
 're',
 'release',
 'sys',
 'system',
 'system_alias',
 'uname',
 'uname_result',
 'version',
 'win32_edition',
 'win32_is_iot',
 'win32_ver']

In [74]:
platform.uname()

uname_result(system='Windows', node='Pavlos', release='11', version='10.0.26200', machine='AMD64')

In [75]:
platform.python_version()

'3.13.5'

In [76]:
platform.processor()

'Intel64 Family 6 Model 170 Stepping 4, GenuineIntel'

In [77]:
platform.machine()

'AMD64'

### shutil
great for moving files

In [78]:
import shutil

src = Path(r'D:\_Python\pokus2.txt')
dst = Path(r'D:\_Python\pokus\pokus2.txt')

shutil.move(src, dst)

WindowsPath('D:/_Python/pokus/pokus2.txt')

In [79]:
shutil.move(dst, src) # and lets move it back

WindowsPath('D:/_Python/pokus2.txt')

In [80]:
shutil.copy(src, dst)

WindowsPath('D:/_Python/pokus/pokus2.txt')